apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName | required }}
  namespace: {{ .Values.serviceNamespace | required }}
  name: {{ .Values.serviceName | required }}
spec:
  ports:
    - port: {{ .Values.service.port | required }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName | required }}