# all these values are required
serviceName: oneshotmetricsserver
serviceNamespace: oneshotmetricsserver

testEvent:
  image: docker.io/alpine/curl
  tag: 8.10.0

server:
  image: ghcr.io/imuni4fun/one-shot-metrics-server
  tag: v0.1.17
  logLevel: INFO
  port: 8080
  useExplicitTimestamps: false
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi

service:
  port: 8090

netpol:
  generate: true
  ingress:
    allowedNamespaceMatchLabels: []
    allowedPodMatchLabels: []
  