{{ if ((.Values.netpol).generate) | default false }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName | required "serviceName is required" }}
  name: "allow-{{ .Values.serviceName | required "serviceName is required" }}-ingress"
  namespace: {{ .Values.serviceNamespace | required "serviceNamespace is required" }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.serviceNamespace | required "serviceNamespace is required" }}
    {{- range $ns := (.Values.netpol.ingress).allowedNamespaceMatchLabels }}
    - namespaceSelector:
        matchLabels:
          name: {{ $ns | required "netpol.ingress.allowedNamespaceMatchLabels must be valid" }}
    {{- end }}
    {{- range $ns := (.Values.netpol.ingress).allowedPodMatchLabels }}
    - podSelector:
        matchLabels:
          name: {{ $ns | required "netpol.ingress.allowedPodMatchLabels must be valid" }}
    {{- end }}
  policyTypes:
  - Ingress
{{ end }}