{{ if .Values.netpol.generate }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName | required "serviceName is required" }}
  name: "allow-{{ .Values.serviceName | required "serviceName is required" }}-ingress"
  namespace: {{ .Values.serviceNamespace | required "serviceNamespace is required" }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.serviceNamespace | required "serviceNamespace is required" }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.serviceName | required "serviceName is required" }}
  policyTypes:
  - Ingress
{{ end }}