apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName | required "serviceName is required" }}
  name: {{ .Values.serviceName | required "serviceName is required" }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Values.serviceNamespace | required "serviceNamespace is required" }}
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.serviceName | required "serviceName is required" }}