apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName | required "serviceName is required" }}
  namespace: {{ .Values.serviceNamespace | required "serviceNamespace is required" }}
  name: {{ .Values.serviceName | required "serviceName is required" }}
spec:
  ports:
    - port: {{ .Values.service.port | required "service.port is required" }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName | required "serviceName is required" }}