name: Package Helm Charts

on:
  push:
    tags:
      - 'helm-v[0-9]+.[0-9]+.[0-9]+'

jobs:

  release:
    name: Package helm chart and create release
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"  
      
      # - name: Install Helm
      #   uses: azure/setup-helm@v4
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          pages_branch: helm_package
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
